---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name:  b
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name:  a
  annotations:
    component-operator.cs.sap.com/delete-policy: orphan
    # component-operator.cs.sap.com/adoption-policy: always
data:
  foo: bar
