apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}-2
  name:  {{ name }}
data:
  lookup-testing: {{ (mustLookup "v1" "ConfigMap" "testing" "data").data.foo }}
  localLookup-testing: {{ (mustLocalLookup "v1" "ConfigMap" "testing" "data").data.foo }}
