apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}-2
  name:  {{ name }}
  annotations:
    component-operator.cs.sap.com/reapply-interval: "5m"
data:
  a: bdevops-knowledge-vectorizer
