apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name:  {{ name }}
data:
  lookup-testing: {{ (mustLookup "v1" "ConfigMap" "testing" "data").data.foo }}
  localLookup-testing: {{ (mustLocalLookup "v1" "ConfigMap" "testing" "data").data.foo }}
  localLookup-default: {{ (mustLocalLookup "v1" "ConfigMap" "default" "data").data.foo }}
