apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name:  {{ name }}
  annotations:
    a1: v1
    a2: v2
data:
  type: kustomize
  foo: |
    {{ . | toJson }} 
  bar: "2"
  substitute: ${var}
  serverInfo: {{ kubernetesVersion }}
  newkey: newval
