---
apiVersion: core.cs.sap.com/v1alpha1
kind: Component
metadata:
  namespace: default
  name: b2 
spec:
  sourceRef:
    fluxGitRepository:
      name: component-test
  path: b2 
  requeueInterval: 10m
