---
apiVersion: core.cs.sap.com/v1alpha1
kind: Component
metadata:
  namespace: ns1
  name: test
spec:
  name: exploit
  namespace: ns-privileged
  missingNamespacesPolicy: DoNotCreate
  sourceRef:
    fluxGitRepository:
      namespace: default
      name: component-test
  path: c1
  # serviceAccountName: the-admin
