---
apiVersion: core.cs.sap.com/v1alpha1
kind: Component
metadata:
  namespace: ns4
  name: test
spec:
  missingNamespacesPolicy: DoNotCreate
  sourceRef:
    fluxGitRepository:
      namespace: default
      name: component-test
  path: c4
  # serviceAccountName: the-admin
