---
apiVersion: core.cs.sap.com/v1alpha1
kind: Component
metadata:
  namespace: default 
  name: test
spec:
  sourceRef:
    fluxGitRepository:
      name: component-test
  path: job 
  values:
    foo: bar2
