---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: ns
  name: a
spec:
  sourceRef:
    kind: GitRepository
    name: component-test
    namespace: default
  path: ka
  prune: true
  interval: 5m
