---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: b1 
spec:
  sourceRef:
    kind: GitRepository
    name: component-test
  targetNamespace: default
  path: b1
  prune: true
  interval: 5m
  timeout: 3m
  wait: true
