---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: default 
  name: test
spec:
  sourceRef:
    kind: GitRepository
    name: component-test
    namespace: default
  targetNamespace: default
  path: job
  prune: true
  interval: 5m
  wait: true
