---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name:  a
  annotations:
    component-operator.cs.sap.com/reconcile-policy: once
    component-operator.cs.sap.com/update-policy: recreate
data:
  foo: bar 
