{%- $hanaInstanceId := .hanaInstanceId %}
{%- if not $hanaInstanceId %}
{%- $hanaInstanceId = (mustLookup "v1" "ConfigMap" namespace (printf "hana-db-%s" .appName)).data.instanceID %}
{%- end %}
{%- $aicoreDeploymentId := (mustLookup "v1" "ConfigMap" namespace (printf "%s--%s" namespace .aicoreModelName)).data.deploymentId %}
# TODO: considering componentDigest might not be enough; we should consider in addition all data 
# retrieved from the cluster by lookup/mustLookup (at least if these data could change)
{% $revision := 1 %}
{% $digests := dict "componentDigest" componentDigest "hanaInstanceId" $hanaInstanceId "aicoreDeploymentId" $aicoreDeploymentId | toPrettyJson %}
---
{%- $cm := lookup "v1" "ConfigMap" namespace "revision" %}
{%- if $cm %}
{%- $revision = $cm.data.revision | atoi %}
{%- if ne $digests $cm.data.digests %}
{%- $revision = $revision | add1 %}
{%- end %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: revision
  resourceVersion: "{% $cm.metadata.resourceVersion %}"
data:
  revision: "{% $revision %}"
  digests: |-
    {%- $digests | nindent 4 %}
{%- else %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: revision
data:
  revision: "{% $revision %}"
  digests: |-
    {%- $digests | nindent 4 %}
{%- end %}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: y-{% $revision %}
