---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "37ab3fdbd8680e9207915ec514d724f274713f45"
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "90"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
