---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "6e4c9082e44cd1c5bfb02c957bf2afcd34484089"
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "90"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
