---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "552f892cbbba943aec50a87849f0697327cbd6cd"
        {{- fail "oops" }}
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "150"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
