---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "6b9ecd133548a6d1eae1105e3f65dc4129b5027d"
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "600"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
