---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "ba2b940ead59e8a7aaf9a6c4fb652fcd149ce232"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "120"
          restartPolicy: Never
