---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "b3c618a9f8f60feed3b81300ae0368e4ab33c985"
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "90"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
