---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "c869acd7a0a88c67196bdaf6ea955c76782296b7"
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "600"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
