---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "9e233ea0a41175fe230381cc72867e85af3437f8"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "300"
          restartPolicy: Never
