---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "0d6b343b8e278ac56bdbcfb0bd691be2f42e8ee2"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "300"
          restartPolicy: Never
