---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "c3f38785ad547614b859c0f98c016ce130540490"
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "60"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
