---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "51df37342b9cb55f458d461f2be89e145cc21023"
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "120"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
