---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b1
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "082e8ed1fd55a7c93410b9bf66640f68e26c3834"
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1 
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "90"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
