---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b2
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "f292d76e6b32dba842c8bfb43b610e28810fe5cc"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "150"
          restartPolicy: Never
