---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b2
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "fa79e54e17938633f54b9db3d28aaf55c3ebf140"
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "150"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
