---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b2
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "34ee8d928c412d98e3f893cafa4b8f85a4aa2ca6"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "300"
          restartPolicy: Never
