---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b2
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "335511e1d248020615eb9cb2fabfed738994a3fb"
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "300"
          restartPolicy: Never
