---
apiVersion: batch.cs.sap.com/v1alpha1
kind: ReactiveJob
metadata:
  name: b2
spec:
  jobTemplate:
    metadata:
      annotations:
        sha: "e2b25907b7c1af9dfb487cffc90731e57bd0e26b"
        {{- if .foo }}
        foo:  {{ .foo }}
        {{- end }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - image: alpine
            name: test
            command:
            - sleep
            - "150"
          restartPolicy: Never
          terminationGracePeriodSeconds: 5
