name: Deploy

on:
  push

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Wait for check suites to complete
      uses: sap-contributions/await-check-suites@master
      with:
        intervalSeconds: 10
        timeoutSeconds: 1800
        failStepIfUnsuccessful: true
        appSlugFilter: github-actions
